# Generated by Django 3.2.20 on 2025-04-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
